apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: akeyless-secret-store
spec:
  provider:
    akeyless:
      # URL of your akeyless API
      akeylessGWApiURL: "https://api-sbx.tp.cs.akeyless.fans"
      authSecretRef:
        kubernetesAuth:
          accessID: "p-kwkhm04xnnuakm"
          k8sConfName: "/Sandbox/4 - Kubernetes/cg-akl-azure"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount that will be used for Akeyless RBAC
          serviceAccountRef:
            name: "cg-akl-azure-k8s-sa"
