apiVersion: v1
kind: Namespace
metadata:
  name: akeyless-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-token-reviewer
  namespace: akeyless-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-token-reviewer-token
  namespace: akeyless-auth
  annotations:
    kubernetes.io/service-account.name: gateway-token-reviewer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: gateway-token-reviewer
    namespace: akeyless-auth

